### ISSUE TITLE
Why the projection crs need to be centered in Helsinki when calculating the distance?

### ISSUE THREAD

**Issue by woodwm** [Automating-GIS-processes/site#100]
Hi, I have a question in [Calculating distances](https://autogis-site.readthedocs.io/en/stable/notebooks/L2/calculating-distances.html).

I am wondering why the projection crs need to be centered in Helsinki rather than simply using the original crs 3035. Does it increase the accuracy of calculating distance?

**Comment by christophfink** [comment]
This is not part of the course material anymore. To answer your question: I don’t know. Might be that the original author of that part of the course thought that it looks nice if the centre of the map is to/from where the distances are calculated. 

Definitely no deeper technical reason I can grasp.
