### ISSUE TITLE
The hyperlink to course website does not work

### ISSUE THREAD

**Issue by Saareem** [Automating-GIS-processes/site#139]
When clicking the link on the README, you don't get to the course website. It only returns custom 404. 

The link in question is https://autogis-site.readthedocs.io/en/latest/course-info/course-info.html. It's located on the bottom of the README in the "Contact" section. 
![image](https://user-images.githubusercontent.com/11333369/199251693-1665f393-17a2-45b0-88f9-2258aca37e45.png)

**Comment by christophfink** [comment]
Thanks! Fixed it
