### ISSUE TITLE
Clean the data repository

### ISSUE THREAD

**Issue by HTenkanen** [Automating-GIS-processes/site#42]
The `./data` repository contains quite large files that would be good to clean. However, check that doing that does not break anything in terms of building the materials.

**Comment by christophfink** [comment]
I’m doing this during the update for autumn 2022. To further clean things up, I also:
- eliminated the split directories for lessons and notebooks
- converted everything to myst-markdown (easier and more detailed versioning)
- implemented an automated grader using pytest (see https://github.com/Automating-GIS-processes-2022/ repositories), with immediate feedback after each commit and push,
- added MANY readme instructions to this repository, the docker image repo, the notebook repo

and probably still more. Anyway, closing this issue as part of cleaning up.
