### ISSUE TITLE
Automating-GIS-Processess. Lesson 3

### ISSUE THREAD

**Issue by AdrianKriger** [Automating-GIS-processes/site#64]
Hi.

In Lesson 3 of Automating-GIS-Processes: nearest-neighbour.ipynb - (`def get_nearest_values_`) you might consider replacing `.get_values()[0]` with `.to_numpy()[0]`.

This is a great resource.
Thank you.
Adrian.

**Comment by VuokkoH** [comment]
Hi @AdrianKriger! thanks for noting this, the syntax is now updated as `.values[0]`.
