### ISSUE TITLE
Lesson 2: read/write different file formats - missing files

### ISSUE THREAD

**Issue by muxevola** [Automating-GIS-processes/site#67]
I'm not able to find anywhere the files "Finland.*" in multiple formats (i.e. tab, gdb, gpkg, kml, geojson, shp). I've looked not only under L2_data folder, but everywhere. I've even looked under the 2018 course's data folders.

The file is also missing if I run the notebook in Binder.

Do I need to download it from somewhere else?

Thanks!

**Comment by dominijk** [comment]
Thanks for the excellent guide it might be worth including the `to_postgis` method now avaialble.

https://geopandas.readthedocs.io/en/latest/docs/reference/api/geopandas.GeoDataFrame.to_postgis.html?highlight=postgis#geopandas.GeoDataFrame.to_postgis

**Comment by VuokkoH** [comment]
@muxevola thanks for noting this and sorry for the trouble. The Finland polygon is now available in different file formats in the repository under: https://github.com/Automating-GIS-processes/site/tree/master/source/notebooks/L2/data. At the same time, the main point of this section is to demonstrate the syntax for reading and writing data from various formats that you can then apply to your own data :)

**Comment by VuokkoH** [comment]
@dominijk thanks for noting, should indeed include `to_postgis` in here! Will do so when iterating these materials further for pythongis.org.
