### ISSUE TITLE
Lesson 3: AttributeError: 'GeoSeries' object has no attribute 'get_values'

### ISSUE THREAD

**Issue by muxevola** [Automating-GIS-processes/site#68]
The function `get_nearest_values()` contains the following line:
```python
nearest_value = nearest_data[value_column].get_values()[0]
```
which fails with the above error.

The method `get_values()` is deprecated since Pandas version 0.25.0. You can use `DataFrame.values` instead.

I'm using Pandas v1.0.4 and GeoPandas v0.7.0.

Working code:
```python
nearest_value = nearest_data[value_column].values[0]
```

**Comment by VuokkoH** [comment]
Hi @muxevola, thanks for noting this! The syntax has indeed changed - this is now fixed.
