### ISSUE TITLE
distance computations in L3 nearest neighbor

### ISSUE THREAD

**Issue by esrasuel** [Automating-GIS-processes/site#69]
I think there is a problem with the computation of distances in L3 nearest neighbor function due to a mix up of lat/lng order. 

For example, if you look at the output 7 in nearest-neighbor-faster.ipynb :

the distance between  POINT (24.85584 60.20727) and POINT (24.85745 60.20749) is 180.521584

when I try to replicate with [haversine ](https://pypi.org/project/haversine/) or [sklearn ](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.haversine_distances.html), I get 92 meters instead. 

I also tried switching lat/lng pairs, then you get the 180.521584 meter output. But my understanding is that the correct distance should be 92m.

**Comment by HTenkanen** [comment]
@esrasuel Thanks for pointing this out! We were also approached by another user who pointed out the same thing. We will fix this.
