### ISSUE TITLE
Raster lesson - 404 error for data file download

### ISSUE THREAD

**Issue by chrisdunley** [Automating-GIS-processes/site#98]
Great course.  Have run into a problem with the raster session - the link to download data for the lesson is broken and returns a 404 error.  The link is http://www.helsinki.fi/science/accessibility/opetus/autogis/L5_data.zip and it appears in the first cell of the reading-raster notebook.
Please update the link as the data files are needed especially for later sessions.
Thanks
Chris

**Comment by christophfink** [comment]
I think this is not true anymore for last year’s and definitely not for this year’s iteration of the course, closing this issue.
